# Generated by Django 3.0.10 on 2022-05-27 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('transmission', models.CharField(max_length=30)),
                ('air_conditioning', models.BooleanField()),
                ('price_per_day', models.FloatField()),
                ('avability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('document_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=120)),
                ('number_of_cars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('rental', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.Rental')),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_license', models.CharField(max_length=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Client')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.CarBrand')),
                ('car_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.CarCategory')),
            ],
        ),
        migrations.CreateModel(
            name='CarClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=None)),
                ('date_of_rental', models.DateField()),
                ('date_of_return', models.DateField()),
                ('number_of_days', models.IntegerField()),
                ('days_to_return', models.IntegerField()),
                ('penalties', models.BooleanField(default=False)),
                ('amount_of_penalties', models.FloatField(default=0)),
                ('insurance', models.BooleanField()),
                ('total_cost', models.FloatField()),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.Car')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.Client')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.CarModel'),
        ),
        migrations.AddField(
            model_name='car',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Rental'),
        ),
    ]
