# Generated by Django 3.0.10 on 2022-05-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='capacity',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='capacity',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manualna', 'Manualna'), ('Automat', 'Automat')], default=('Manualna', 'Manualna'), max_length=30),
        ),
    ]
