# Generated by Django 3.0.10 on 2022-05-31 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0003_auto_20220531_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='client',
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
