# Generated by Django 3.0.10 on 2022-06-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_auto_20220531_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'permissions': [('rzym_view_rental', 'obiektowy rental view')]},
        ),
    ]
