# Generated by Django 3.0.10 on 2022-06-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_auto_20220531_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'permissions': [('rzym_view_car', 'rzym car view'), ('londyn_view_car', 'londyn car view'), ('paryz_view_car', 'paryz car view')]},
        ),
    ]
