# Generated by Django 3.0.10 on 2022-06-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_auto_20220606_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'permissions': [('rzym_view_car', 'obiektowy car view')]},
        ),
    ]
