# Generated by Django 3.0.10 on 2022-06-06 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_auto_20220606_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'permissions': [('rzym_view_car', 'rzym car view'), ('londyn_view_car', 'londyn car view'), ('paryz_view_car', 'paryz car view')]},
        ),
    ]
