# Generated by Django 3.0.10 on 2022-06-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_auto_20220607_1313'),
        ('viewer', '0008_auto_20220607_1040'),
    ]

    operations = [
    ]
