# Generated by Django 3.0.10 on 2022-06-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_merge_20220607_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={},
        ),
    ]
