# Generated by Django 3.0.10 on 2022-06-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_auto_20220607_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='picture',
            field=models.ImageField(default=None, upload_to='picture'),
        ),
    ]
