# Generated by Django 3.0.10 on 2022-06-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_auto_20220607_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='picture',
        ),
    ]
