# Generated by Django 3.0.10 on 2022-06-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_remove_carmodel_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='picture',
            field=models.ImageField(default=False, upload_to='picture'),
        ),
    ]
