# Generated by Django 3.0.10 on 2022-06-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_auto_20220607_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='picture',
            field=models.ImageField(default=None, upload_to='viewer/picture'),
        ),
    ]
