# Generated by Django 3.0.10 on 2022-06-08 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_task'),
        ('viewer', '0016_auto_20220607_2055'),
    ]

    operations = [
    ]
