# Generated by Django 3.0.10 on 2022-06-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0017_merge_20220608_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='picture',
            field=models.ImageField(default=False, upload_to='viewer/picture'),
        ),
    ]
